language: ruby
cache: bundler

rvm:
  - 2.4.1
  - 2.3.3
  - 2.2.7

env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql

gemfile:
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile

sudo: false

bundler_args: '--without local_development --jobs 3 --retry 3'

before_install:
   - gem install bundler

script: bundle exec rake

matrix:
<<<<<<< HEAD
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_5.0.gemfile
=======
>>>>>>> f5222d8... Drop support for old version of ActiveRecord and Ruby and prepare rel… (#828)
  fast_finish: true
